name: ChatBridge
version: 1.1.2
author: JaxkDev
main: JaxkDev\ChatBridge\Main
src-namespace-prefix: JaxkDev\ChatBridge
description: Plugin to bridge the chat between minecraft and discord using the DiscordBot API
website: https://github.com/DiscordBot-PMMP/ChatBridge

api: 5.0.0
depend:
  - DiscordBot