---
version: 2

presence:
  enabled: true
  status: "Idle"
  type: "Playing"
  message: "on a PMMP Server!"

messages:
  discord:
    enabled: true
    from_channels:
      - "123456789"
    format: "[Discord] §a{NICKNAME}§r > §c{MESSAGE}"
    to_minecraft_worlds: "*"

  minecraft:
    enabled: true
    from_worlds: "*"
    format:
      text: "New Message"
      embed:
        enabled: true
        title: null
        description: "{USERNAME} ```{MESSAGE}```"
        url: null
        author: null
        footer: "ChatBridge"
        colour: 0xEE5959
        time: true
        fields: []
    to_discord_channels:
      - "123456789"


commands:
  minecraft:
    enabled: true
    from_worlds: "*"
    format:
      text: "Command executed"
      embed:
        enabled: true
        title: "{USERNAME}"
        description: "/{COMMAND} {ARGS}"
        author: "ChatBridge"
        url: null
        footer: "This is a footer"
        time: true
        colour: 0x49F9C1
        fields:
          - name: "Field Name"
            value: "Field Value"
            inline: false
    to_discord_channels:
      - "123456789"


leave:
  discord:
    enabled: true
    servers:
      - "123456789"
    format: "§a{NICKNAME} §cHas left the discord server :("
    to_minecraft_worlds: "*"

  minecraft:
    enabled: true
    ignore_transferred: true
    format:
      text: ""
      embed:
        enabled: true
        title: "Player Left"
        description: "- **{USERNAME}** left, reason: {REASON}"
        author: "ChatBridge"
        url: null
        footer: "This is a footer"
        time: true
        colour: 0xEE5959
        fields:
          - name: "Field Name"
            value: "Field Value"
            inline: false
    to_discord_channels:
      - "123456789"


join:
  discord:
    enabled: true
    servers:
      - "123456789"
    format: "§a{USERNAME} §cHas joined the discord server :)"
    to_minecraft_worlds: "*"

  minecraft:
    enabled: true
    format:
      text: ""
      embed:
        enabled: true
        title: "Player Joined"
        description: "+ **{USERNAME}**"
        author: "ChatBridge"
        url: null
        footer: "This is a footer"
        time: true
        colour: 0xEE5959
        fields:
          - name: "Field Name"
            value: "Field Value"
            inline: false
    to_discord_channels:
      - "123456789"


transferred:
  minecraft:
    enabled: true
    format:
      text: ""
      embed:
        enabled: true
        title: "Player Transferred"
        description: "**{USERNAME}** -> `{SERVER_ADDRESS}:{SERVER_PORT}`"
        author: "ChatBridge"
        url: null
        footer: "This is a footer"
        time: true
        colour: 0xEE5959
        fields:
          - name: "Field Name"
            value: "Field Value"
            inline: false
    to_discord_channels:
      - "123456789"

...